{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"Infinity","kind":"identifier"}]}]}],"metadata":{"role":"symbol","title":"EvaluationError.Infinity","roleHeading":"Case","externalID":"s:11SoulverCore15EvaluationErrorO8InfinityyA2CmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Infinity","kind":"identifier"}],"modules":[{"name":"SoulverCore"}],"symbolKind":"case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/app.soulver.core\/documentation\/SoulverCore","doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError"]]},"identifier":{"url":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError\/Infinity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Not really infinity, but a number too large for us to handle"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/soulvercore\/evaluationerror\/infinity"]}],"references":{"doc://app.soulver.core/documentation/SoulverCore/EvaluationError":{"identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError","kind":"symbol","abstract":[{"type":"text","text":"All errors that SoulverCore can produce as a result of a calculation"}],"url":"\/documentation\/soulvercore\/evaluationerror","role":"symbol","title":"EvaluationError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EvaluationError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EvaluationError"}],"type":"topic"},"doc://app.soulver.core/documentation/SoulverCore":{"title":"SoulverCore","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore","role":"collection","abstract":[{"text":"A powerful natural language calculation engine","type":"text"}],"type":"topic","url":"\/documentation\/soulvercore","kind":"symbol"},"doc://app.soulver.core/documentation/SoulverCore/EvaluationError/Infinity":{"url":"\/documentation\/soulvercore\/evaluationerror\/infinity","type":"topic","abstract":[{"text":"Not really infinity, but a number too large for us to handle","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/app.soulver.core\/documentation\/SoulverCore\/EvaluationError\/Infinity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"Infinity"}],"title":"EvaluationError.Infinity"}}}